### ISSUE TITLE
Difference on NSE and R2

### ISSUE THREAD

**Issue by walking-shadow** [earthnet2021/earthnet-models-pytorch#45]
The calculation formulas for NSE and R2 are essentially the same, but their purposes are different. Why are the values of these two indicators calculated in the paper different?

**Comment by vitusbenson** [comment]
they are not calculated identically,
R2 = r**2, with r the pearson correlation coefficient https://en.wikipedia.org/wiki/Pearson_correlation_coefficient#For_a_sample
NSE = Sum((Pred-Targ)**2) / Sum((Targ-Mean(Targ))**2) https://en.wikipedia.org/wiki/Nash%E2%80%93Sutcliffe_model_efficiency_coefficient

See https://github.com/earthnet2021/earthnet-models-pytorch/blob/main/scripts/score_en21x_v2.py#L45

**Comment by walking-shadow** [comment]
Thank you for your explanation. I misunderstood the calculation formula for R2 as 1 - SSE/SST, which is the same as the formula for NSE.
